name: remove-unused-deps
on:
  push:
    branches:
      - main
    paths:
      - package.json
jobs:
  remove-unused-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: remove unused deps
        run: ./remove-unused-deps.sh ./package.json
      - name: install
        run: npm install
      - name: commits
        run: |
          git config user.name 'Masahiro Yamauchi'
          git config user.email 'sgt.yamauchi@gmail.com'
          git add ./package*.json
          git commit -m "remove unused dependencies"
      - name: create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          title: Remove unused dependencies
          assignees: ${{ github.actor }}
          reviewers: ${{ github.actor }}
